### ISSUE TITLE
Failed to process path: xxx => Unexpected result count: 0, expected 1

### ISSUE THREAD

**Issue by jarmo** [duplicati/duplicati#1400]
Quite often Duplicati 2 shows warnings like this while backupping:
`Failed to process path: /var/log/mail.log => Unexpected result count: 0, expected 1`
##

**Comment by kenkendk** [comment]
That is an issue with the database being inconsistent.

Can you try a repair command?

**Comment by jarmo** [comment]
During next backup i get warnings for different files - e.g. it seems that this warning is not related with the same file always and these warnings will disappear with next backups. So, i don't see any point to repair when it will disappear with next backup.

Having that additional information - is it still possible that database is inconsistent and that's why these warnings appear?

**Comment by jarmo** [comment]
I'm getting that warning quite often also for duplicati's own database and it's journal specified by `--dbpath` parameter:
`[Failed to process path: /home/duplicati/duplicati-backup-local-db => Unexpected result count: 0, expected 1, Failed to process path: /home/duplicati/duplicati-backup-local-db-journal => Unexpected result count: 0, expected 1]`

**Comment by kenkendk** [comment]
Can you try to set --log-level=profiling (you can do it in the GUI log-window)?

With that level of information, it will log all SQL queries sent to the database, so I can see which of the SQL statements that fail.

**Comment by jarmo** [comment]
I'm using `Duplicati.CommandLine.exe` with `mono` and added `--log-level=profiling` to that command line, but didn't see any additional output. Is this switch not taken into account when using CLI?

**Comment by kenkendk** [comment]
Yes, it is taken into account, but the log data goes into the log file, not stdout.
You need to add `--log-file=/home/user/logdata.txt`

**Comment by jarmo** [comment]
This is what i see in the log:
```
2015-07-22 12:23:51Z - Profiling: ExecuteScalar: INSERT INTO "Blockset" ("Length", "FullHash") VALUES (?, ?); SELECT last_insert_rowid(); took 00:00:00.000
2015-07-22 12:23:51Z - Warning: Failed to process path: /home/btsync/duplicati-backup-local-db-journal
System.Exception: Unexpected result count: 0, expected 1
  at Duplicati.Library.Main.Database.LocalBackupDatabase.AddBlockset (System.String filehash, Int64 size, Int32 blocksize, IEnumerable`1 hashes, IEnumerable`1 blocklistHashes, System.Int64& blocksetid, IDbTransaction transaction) [0x0000
0] in <filename unknown>:0
  at Duplicati.Library.Main.Operation.BackupHandler.AddFileToOutput (System.String filename, Int64 size, DateTime lastmodified, IMetahash metadata, IEnumerable`1 hashlist, System.String filehash, IEnumerable`1 blocklisthashes) [0x00000]
in <filename unknown>:0
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (System.String path, FileAttributes attributes) [0x00000] in <filename unknown>:0

2015-07-22 12:23:51Z - Information: Adding directory /home/backup/duplicati/
```

I'm not sure there's anything valuable in there...

**Comment by kenkendk** [comment]
It tells me exactly where the error occurs, so at least some value to me :).

**Comment by kenkendk** [comment]
I have tried to figure out what causes this, and come up blank ...

The error seems to happen because the file in question contains some data block that is not found in the database. Looking at the filenames, could this be caused by the file being changed during the backup?

I have added some additional debug tracing values in commit 3182a22 and I will make a new canary with this active, hopefully tomorrow.

@jarmo and @JonasDralle if you can try with this new version, and report the values that would help out a great deal. Also, if you have observed some similarity between the files that cause this error, this would also help.

**Comment by jarmo** [comment]
If I'm not mistaken then I haven't seen that issue recently and searching from my e-mails sent by Duplicati backup process I see last time this error occurred about a month ago and I've been updating Duplicati in the mean time.

I've still updated to last version of Duplicati and if I will see it happen again then I'll let you know.

I will close this issue for now and reopen when necessary. Thanks!

**Comment by jarmo** [comment]
Reopening it since just saw this problem happen:
```
Failed to process path: c:\bin\backup\backup-emperor-db-c-journal => Unexpected result count: 0, expected 1, hash: O7YfDjKPOX0ENJhmNrdij6Xim4cZqkWGbS3elC9Lfxk=, size: 102400, blocksetid: 349313, ix: 36, fullhash: t5a/YMP+33+mdEusNB6HSqHGRaJULbWeCmd2PwpHzNI=, fullsize: 4184160
```

What a coincidence after closing it.

**Comment by kenkendk** [comment]
Again, this appear to happen on a file that would be likely to change during the backup process.
It should not cause problems if the file is rewritten during the backup, but I think that is what causes this issue.

**Comment by jarmo** [comment]
Yes, that's probably the case, but why would it even cause any problems when snapshots are used with ```--snapshot-policy=auto```?

**Comment by kenkendk** [comment]
If you use `auto` it is not guaranteed that the snapshot will be created. It is intended as a "I would like a snapshot, but prefer a backup without snapshots rather than no backup if snapshots could not be created" option. You need to use the `required` setting to get a "snapshot or fail" setting.

**Comment by jarmo** [comment]
Isn't duplicati spitting out any warnings or anything if snapshot request fails?
Isn't it quite an expected situation where backupped files might change during backup?

**Comment by kenkendk** [comment]
If you use the setting `auto` you get no warning. In hindsight, a better name would perhaps have been `optional`. 

If you use the setting `on`, you get a warning if the snapshot fails.

And yes, it is an expected situation that the files change during the backup, and it worked last time I tested it. But I am guessing that changing the file is part of the problem.

**Comment by jarmo** [comment]
I'm also seeing same warnings on Ubuntu - could there be a same problem taking into account file system differences?

**Comment by andys8** [comment]
+1 to fix this issue regarding beta release

**Comment by kenkendk** [comment]
I believe this is now fixed.

**Comment by AGSPhoenix** [comment]
My backups have been failing for some time now, and taking a look at the log, the errors are the checks Ken added:

```
Errors: [
    2018-12-28 14:58:05 -05 - [Error-Duplicati.Library.Main.Database.LocalBackupDatabase-CheckingErrorsForIssue1400]: Checking errors, related to #1400. Unexpected result count: 0, expected 1, hash: BeBYGSVg+j0f8AmQsTD8NckpeSPdvNzvwq2DhYvgmd8=, size: 102400, blocksetid: 3537187, ix: 72, fullhash: 8KOeYdHZvWmir7araJpUXRGfTgq9e9ALaz5W5rnofkQ=, fullsize: 7546081,
    2018-12-28 14:58:05 -05 - [Error-Duplicati.Library.Main.Database.LocalBackupDatabase-FoundIssue1400Error]: Found block with ID 15060394 and hash BeBYGSVg+j0f8AmQsTD8NckpeSPdvNzvwq2DhYvgmd8= and size 91287,
    2018-12-28 14:58:05 -05 - [Error-Duplicati.Library.Main.Database.LocalBackupDatabase-CheckingErrorsForIssue1400]: Checking errors, related to #1400. Unexpected result count: 0, expected 1, hash: 3DfijKh74KvcIYnPuMXn4K69zHpej5z64g+ER5x25t8=, size: 102400, blocksetid: 3537189, ix: 99, fullhash: MQ6mycSt4Ssa7HGDGb81yG3ZaMxol/LZhuCO1XFGDQc=, fullsize: 10322006,
    2018-12-28 14:58:05 -05 - [Error-Duplicati.Library.Main.Database.LocalBackupDatabase-FoundIssue1400Error]: Found block with ID 15060499 and hash 3DfijKh74KvcIYnPuMXn4K69zHpej5z64g+ER5x25t8= and size 98271,
    2018-12-28 14:58:06 -05 - [Error-Duplicati.Library.Main.Database.LocalBackupDatabase-CheckingErrorsForIssue1400]: Checking errors, related to #1400. Unexpected result count: 0, expected 1, hash: hIl63cl1KjfD3BXj5ZoNzmiO69shf/Rtz8U64vlIPME=, size: 102400, blocksetid: 3537191, ix: 131, fullhash: 5+Gf5aD5zrXMGOrpGPjW1uKxKUrini65xxlclie2ozo=, fullsize: 13521324,
...
]
```

I have older backups of this data, and don't mind leaving things broken for a while while investigating. Any suggestions for how to go about debugging this?

**Comment by mxxcon** [comment]
Ever since I upgraded my mbp to `2.0.4.5_beta_2018-11-28` my backups started throwing these errors:
```
    Errors: [
        2019-01-03 11:12:38 -05 - [Error-Duplicati.Library.Main.Database.LocalBackupDatabase-CheckingErrorsForIssue1400]: Checking errors, related to #1400. Unexpected result count: 0, expected 1, hash: OsiQFi/obSoFKXMdWcJjP1GsA21bLXQvRe0j11VVKr4=, size: 25760, blocksetid: 145393, ix: 213, fullhash: A82TaXVMvNj7Xua9CVI65Q1FRQMsC74znQ9k/DhSBZs=, fullsize: 21836960,
        2019-01-03 11:12:38 -05 - [Error-Duplicati.Library.Main.Database.LocalBackupDatabase-FoundIssue1400Error]: Found block with ID 281305 and hash OsiQFi/obSoFKXMdWcJjP1GsA21bLXQvRe0j11VVKr4= and size 19568
    ]
```
I have tried to "Repair" and "Recreate(delete and repair)" my database, but that doesn't fix the errors.

**Comment by Pectojin** [comment]
@kenkendk

**Comment by MM-John** [comment]
I can report that `--snapshot-policy=on` appeared to remove these errors for me. That's over just 2 runs: 1 without, 1 with. https://forum.duplicati.com/t/checking-errors-related-to-1400-unexpected-result-count-0-expected-1/5876

**Comment by nils-se** [comment]
Same goes for me on version "2.0.4.5_beta_2018-11-28" on a fresh Xubuntu 18.04 System. 

repair and "delete and repair" didn't solve it. 

snapshot-policy=on results in

"Warning-Duplicati.Library.Main.Operation.BackupHandler-SnapshotFailed"
with exit-code: 255
"Error: unable to determine volume group (VG) for /home/*username*/"

probably because not run as superuser?

**Comment by mxxcon** [comment]
It still errors for me w/o `--snapshot-policy=`, with `auto` and with `on`.
With `on` I also get this "warning": 
>Error message: System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/Applications/Duplicati.app/Contents/Resources/lvm-scripts/find-volume.sh', CommandLine='"/Users/my_user/"', CurrentDirectory='', Native error= Cannot find the specified file

**Comment by MM-John** [comment]
That looks like Windows. Did you run with "Run as administrator" ie elevated privileges? [Documentation for `--snapshot-policy` says that `on` gives warnings if VSS fails](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#snapshot-policy). Your situation kinda looks like that.

You can start Duplicati with privs in Windows by right clicking and selecting Run as administrator.

But also on windows, the default `Duplicati.GUI.TrayIcon.exe` installation creates a shortcut in in the `c:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup` folder. This is the shortcut that auto-starts Duplicati when Windows starts. If you're going to use `--snapshot-policy` you need those privs, but this shortcut will start Duplicati _without_ privs, so you have to change this shortcut. 

Right-click the shortcut -> Shortcut tab -> Advanced button -> Run as administrator

Otherwise, even if you start Duplicati with privs the first time, when the system reboots, and it autostarts, it will start un-prived.

Also, this is a global choice for all of Duplicati, all jobs. So if any job uses any option that requires privs, all Duplicati has to always run with privs. You need privs also to access other users' files. And in your own user directory the registry/hive files need both privs and `--snapshot-policy` (VSS).

Another option (I haven't explored) is running as a windows service, which starts with privs automatically. This and other related discussion are in https://duplicati.readthedocs.io/en/latest/02-installation/

**Comment by mxxcon** [comment]
@MM-John Unfortunately, no. Can can be seen from the path in the error message, I'm running it on OSX 10.14.2 (18C54)

**Comment by MM-John** [comment]
@mxxcon Did you ever say whether you were running with privs on OSX (maybe I missed it)? Your errors with `--snapshot-policy=on` may be due to running un-prived.

**Comment by mxxcon** [comment]
> 
> 
> @mxxcon Did you ever say whether you were running with privs on OSX (maybe I missed it)? Your errors with `--snapshot-policy=on` may be due to running un-prived.

Um...I'm running it as I always have in the past. I downloaded .dmg file, opened it and dragged duplicati shortcut into my apps folder and run it from there..however that might be. Afaik in osx if an app needs elevated privileges I'd get prompted for a password to confirm that.

**Comment by MM-John** [comment]
> I tried to set `--snapshot-policy=on` but i'm running Duplicati from inside a docker and the snapshot creation fails, I'll try to inveatigate this.

Did you run with "privs". Eg, `Run as administrator` on windows and `superuser` (`su`) on linux? (I don't know the linux part thoroughly)

**Comment by paolosg** [comment]
@MM-John Jes, the docker run as root, but the source folder is mounted as docker volume so the solution may not be so straightforward.

However as I was saying, this #1400 came up only recently, the same config (w/o snapshot) worked fine for many months. The only thing that changed is that I updated Duplicati.
