### ISSUE TITLE
Restoration of symlink to folders fail

### ISSUE THREAD

**Issue by rledisez** [duplicati/duplicati#1475]
# Environment:
```
# uname -sir
FreeBSD 9.3-RELEASE-p26 FREENAS64
# mono -V
Mono JIT compiler version 4.0.3 (Stable 4.0.3.20/d6946b4 Fri Sep 18 03:21:46 UTC 2015)
```

# Operation:
restoring /path/to/original/dataset to /root/restore

### Original dataset:
```
# ls -l /path/to/original/dataset/var/modules
lrwxrwxrwx  1 foo  foo  11 Jan  1  2015 /path/to/original/dataset/var/modules -> ../modules/
```

### Result
```
# ls -l /root/restore/var/
drwxr-xr-x  2 foo  foo  2 Oct  9 22:04 modules
```

# Problem:
When a symlink target a folder, its restoration "sometimes" fail because the folder is created instead of a symlink. It seems (not sure) it fails when the target is in the selection being restored.

# Log:
```
2015-10-09 21:56:08Z - Warning: Creating missing folder /root/restore/var/modules for target /root/restore/var/modules/
2015-10-09 21:56:08Z - Warning: Failed to apply metadata to file: "/root/restore/var/modules/", message: Unable to create symlink from "/root/restore/var/modules" to "../modules/", error: EEXIST (17)
System.IO.IOException: Unable to create symlink from "/root/restore/var/modules" to "../modules/", error: EEXIST (17)
  at UnixSupport.File.CreateSymlink (System.String path, System.String target) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Snapshots.SystemIOLinux.CreateSymlink (System.String symlinkfile, System.String target, Boolean asDir) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.RestoreHandler.ApplyMetadata (System.String path, System.IO.Stream stream, Boolean restorePermissions) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.RestoreHandler.ApplyStoredMetadata (Duplicati.Library.Main.Database.LocalRestoreDatabase database, Duplicati.Library.Main.Options options, Duplicati.Library.Main.RestoreResults result, Duplicati.Library.Main.Operation.RestoreHandlerMetadataStorage metadatastorage) [0x00000] in <filename unknown>:0 
```

#

**Comment by rledisez** [comment]
I think the problem is here: https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/RestoreHandler.cs#L314-L321

Symlink is created during ApplyMetadata() but the folder is created right before because it does not exist. The condition must check that the folder is not a symlink before creating it.

**Comment by rledisez** [comment]
Or maybe the entry shouldn't be stored in DB with an ending slash. Because having an ending slash for a symlink:
1. trigger this bug: PathGetDirectoryName(/path/to/original/dataset/var/modules/) == /path/to/original/dataset/var/modules
2. makes the entry display as a folder inside the webui, while it is not a folder

**Comment by mach-o** [comment]
Just encountered this too. If anyone comes up with a workaround or a patch, a post here would be much appreciated!

**Comment by ERamseth** [comment]
I can also reproduce this problem.

**Comment by kenkendk** [comment]
@rledisez The reason it is stored with a trailing slash is because Duplicati uses the (mostly internal) convention that folders end with a / (or \ in windows). Storing things this way makes it much easier to do various other operations. 

The `Path.GetDirectoryName()` issue you mention should be handled everywhere, but obviously not here :). Funny that by being broken it also fixes the problem of creating the folder before applying the metadata to it :D.

The reason that the symlink needs to be identified as a folder is for Windows, where you need to do different operations if you want to create a symlink to a folder as opposed to a file.

**Comment by kenkendk** [comment]
I was wrong, the `PathGetDirectoryName()` was fixed some time ago to correctly handle paths ending with /. This means that it should now be fixed. I have added a new check that auto-creates the folder if the target is not a symlink.

**Comment by fcastilloec** [comment]
I'm a new Duplicati user and I just run into this bug.
Duplicati v2.0.5.1_beta_2020-01-18, Ubuntu 18.04 (kernel 5.3.0), Mono v6.8.0.105.

Nothing was restored but Duplicati still showed it as a successful one, with warnings. Which, in my book, it's an error. If what I'm trying to restore is a symlink and that doesn't happen, it should be an error.
I know @kenkendk mentioned that this should be fixed but sadly is not. Here's the log I'm seeing.
```
Warning-Duplicati.Library.Main.Operation.RestoreHandler-MetadataWriteFailed]: Failed to apply metadata to file: "/restore/root/",
message: Unable to create symlink from "/restore/root/" to "/path/backup/directory_symlink/", error: EEXIST (17)
```
Let me know if there's something additional info I can provide in order to fix this.
