### ISSUE TITLE
duplicati  v2.0.0.98-2.0.0.98_preview_2016-01-27 hangs indefinitely while accessing circular filesystem-link

### ISSUE THREAD

**Issue by umgfoin** [duplicati/duplicati#1559]
Problem appeared after updating to preview v2.0.0.98-2.0.0.98_preview_2016-01-27:
Last log-entry  below:

" /home/xxx/.wine/dosdevices/z:" is a circular link to "/"
duplicati bin-dir is /root/duplicati/
database in /root/.config/Duplicati

It looks as if duplicati hang after this action - the mono process was still alive and it was possible to forcibly stop the current task/thread.

This is 
Linux <FQDN> 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

Failed to process path: /home/xxx/.wine/dosdevices/z:/root/.config/Duplicati/JVBDSUHIBX.sqlite-journal
System.Exception: Unexpected result count: 0, expected 1
  at Duplicati.Library.Main.Database.LocalBackupDatabase.AddBlockset (System.String filehash, Int64 size, Int32 blocksize, IEnumerable`1 hashes, IEnumerable`1 blocklistHashes, System.Int64& blocksetid, IDbTransaction transaction) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.AddFileToOutput (System.String filename, Int64 size, DateTime lastmodified, IMetahash metadata, IEnumerable`1 hashlist, System.String filehash, IEnumerable`1 blocklisthashes) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (System.String path, FileAttributes attributes) [0x00000] in <filename unknown>:0 

++umgfoin

**Comment by umgfoin** [comment]
OK, just an update: Excluding the above path and the backup runs through flawlessly as before.
So we can assume duplicati is definitely picky on this circular link.
I`m generally not crazy about such kind of self-referencing traps - anyway, this is the style, the wine-emulator maps Linux-filesystems into the Windows drive-letter schema.
good evening,
++umgfoin.

**Comment by umgfoin** [comment]
The last action "2016-02-03 02:05: Checking for changes..." 

never finished and broke the backup.

/root/.wine/dosdevices/z:/proc/kmsg is a symlink to /proc/kmsg

2016-02-03 02:05: Checking file for changes /root/.wine/dosdevices/z:/proc/kmsg, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 26.01.2016 11:03:43 vs 01.01.0001 00:00:00
2016-02-03 02:05: Failed to process path: /root/.wine/dosdevices/z:/proc/filesystems
{"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object","InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock (System.String hash, System.Byte[] data, Int32 offset, Int32 size, CompressionHint hint) [0x00000] in <filename unknown>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.AddBlockToOutput (System.String key, System.Byte[] data, Int32 offset, Int32 len, CompressionHint hint, Boolean isBlocklistData) [0x00000] in <filename unknown>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (System.String path, FileAttributes attributes) [0x00000] in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2147467261,"Source":"D

**Comment by kenkendk** [comment]
This should have be fixed with b9aacdd24386e48e698c3ed356fb7a2cc5c7b1a9.
There was a problem handling the root path ("/") earlier.

**Comment by umgfoin** [comment]
Kenneth,
thanks for looking into this. Just verified with current build: Not fixed for me.
The backup still hangs, if I include the above symlinked pathes.

No error-message as of now, but duplicati stalled for ~1h without progress,
GUI responsive,
mono process alive and without considerable cpu-activity.

bg armin.

[livelog]
2016-04-01 17:53: RemoteOperationPut took 00:00:01.613
2016-04-01 17:53: Backend event: Put - Completed: duplicati-i979b72ebf27b4e488506423dc1c7f239.dindex.7z.gpg (158,85 KB)
2016-04-01 17:53: Uploaded 158,85 KB in 00:00:00.4838900, 328,27 KB/s
2016-04-01 17:53: Backend event: Put - Started: duplicati-i979b72ebf27b4e488506423dc1c7f239.dindex.7z.gpg (158,85 KB)
2016-04-01 17:53: Starting - RemoteOperationPut
2016-04-01 17:53: RemoteOperationPut took 00:00:53.273
2016-04-01 17:53: Backend event: Put - Completed: duplicati-be7cbb5fedc34476f9bada9325f1ef821.dblock.7z.gpg (55,35 MB)
2016-04-01 17:53: Uploaded 55,35 MB in 00:00:53.1537930, 1,04 MB/s
2016-04-01 17:53: Checking file for changes /home/blank/.wine/dosdevices/z:/proc/kmsg, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 11.02.2016 14:39:20 vs 01.01.0001 00:00:00
2016-04-01 17:53: Including path due to filter: /home/blank/.wine/dosdevices/z:/proc/kmsg => (/home/blank/.wine/*)
2016-04-01 17:53: ExecuteScalar: INSERT INTO "File" ("Path","BlocksetID", "MetadataID") VALUES (?, ? ,?); SELECT last_insert_rowid(); took 00:00:00.000
2016-04-01 17:53: Starting - ExecuteScalar: INSERT INTO "File" ("Path","BlocksetID", "MetadataID") VALUES (?, ? ,?); SELECT last_insert_rowid();
2016-04-01 17:53: ExecuteScalar: SELECT "ID" FROM "File" WHERE "BlocksetID" = ? AND "MetadataID" = ? AND "Path" = ? took 00:00:00.000
2016-04-01 17:53: Starting - ExecuteScalar: SELECT "ID" FROM "File" WHERE "BlocksetID" = ? AND "MetadataID" = ? AND "Path" = ?
2016-04-01 17:53: ExecuteScalar: INSERT INTO "Blockset" ("Length", "FullHash") VALUES (?, ?); SELECT last_insert_rowid(); took 00:00:00.000
2016-04-01 17:53: Starting - ExecuteScalar: INSERT INTO "Blockset" ("Length", "FullHash") VALUES (?, ?); SELECT last_insert_rowid();
2016-04-01 17:53: ExecuteScalar: SELECT "ID" FROM "Blockset" WHERE "Fullhash" = ? AND "Length" = ? took 00:00:00.000
2016-04-01 17:53: Starting - ExecuteScalar: SELECT "ID" FROM "Blockset" WHERE "Fullhash" = ? AND "Length" = ?
2016-04-01 17:53: ExecuteScalar: SELECT "A"."ID" FROM "Metadataset" A, "BlocksetEntry" B, "Block" C WHERE "A"."BlocksetID" = "B"."BlocksetID" AND "B"."BlockID" = "C"."ID" AND "C"."Hash" = ? AND "C"."Size" = ? took 00:00:00.000
2016-04-01 17:53: Starting - ExecuteScalar: SELECT "A"."ID" FROM "Metadataset" A, "BlocksetEntry" B, "Block" C WHERE "A"."BlocksetID" = "B"."BlocksetID" AND "B"."BlockID" = "C"."ID" AND "C"."Hash" = ? AND "C"."Size" = ?
2016-04-01 17:53: ExecuteScalar: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
2016-04-01 17:53: Starting - ExecuteScalar: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
2016-04-01 17:53: New file /home/blank/.wine/dosdevices/z:/proc/filesystems
```

**Comment by umgfoin** [comment]
After forcibly stopping the task, I get the following messages:

Failed to process path: /home/blank/.wine/dosdevices/z:/root/.config/Duplicati/JVBDSUHIBX.sqlite-journal
System.Exception: Unexpected result count: 0, expected 1
  at Duplicati.Library.Main.Database.LocalBackupDatabase.AddBlockset (System.String filehash, Int64 size, Int32 blocksize, IEnumerable`1 hashes, IEnumerable`1 blocklistHashes, System.Int64& blocksetid, IDbTransaction transaction) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.AddFileToOutput (Duplicati.Library.Main.BackendManager backend, System.String filename, Int64 size, DateTime lastmodified, IMetahash metadata, IEnumerable`1 hashlist, System.String filehash, IEnumerable`1 blocklisthashes) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) [0x00000] in <filename unknown>:0 
[...]
Failed to process path: /home/blank/.wine/dosdevices/z:/sys/devices/virtual/tty/tty9/ve_device_add
System.UnauthorizedAccessException: Access to the path "/home/blank/.wine/dosdevices/z:/sys/devices/virtual/tty/tty9/ve_device_add" is denied.
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.Open (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Snapshots.NoSnapshot.OpenRead (System.String file) [0x00000] in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) [0x00000] in <filename unknown>:0

**Comment by umgfoin** [comment]
Issue finally fixed with build 2.0.1.14_canary_2016-04-21.
Verified on Linux 2.6.32-042stab111.12 x64, mono 3.12.1

**Comment by kenkendk** [comment]
Thanks for reporting!
