### ISSUE TITLE
Cannot list any files or folders in "backup to" and "source data" pickers

### ISSUE THREAD

**Issue by kevdliu** [duplicati/duplicati#1662]
Hello, 

After updating to the march 19th version, the file and folder pickers for picking locations to backup to and source data to backup from list nothing. In the ngax UI, clicking on computer or my files doesn't do anything. The triangle on the left side does change direction though. In the old green UI, clicking on the picker just presents an indefinite loading screen. I'm running this on Windows 10 64 bit and I ran Duplicati.GUI.TrayIcon.exe with admin privileges. The last version that worked was the one before the new ngax UI was added (not saying that the new UI is causing the problem because the old UI doesn't work now either). 

Here's the error log:

`2016-03-26 18:48: Request for http://127.0.0.1:8200/api/v1/filesystem?onlyfolders=false&showhidden=true gave error
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.__Error.WriterClosed()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(JsonWriter writer, Object value, JsonContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Duplicati.Server.Serialization.Serializer.SerializeJson(TextWriter sw, Object o, Boolean preventDispose)
   at Duplicati.Server.WebServer.BodyWriter.WriteJsonObject(Object o)
   at Duplicati.Server.WebServer.RESTMethods.Filesystem.Process(String command, String path, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)`

Hope you guys can fix this issue soon and thank you all for this super awesome program!

**Comment by mylemans** [comment]
Could be fixed @ https://github.com/duplicati/duplicati/pull/1667

**Comment by kenkendk** [comment]
I think @mylemans is right, this should be fixed with #1667..
If not, let me know.

**Comment by stanimirivanovde** [comment]
This issue is still present in the latest build of duplicati-experimental: 2.0.1.18_canary_2016-08-10. I can't view files/folders on all of my drives in the Source Data view. This happened when I upgraded to the latest version. It happens on Chrome and Firefox. The following request never returns:

http://127.0.0.1:8300/api/v1/filesystem?onlyfolders=false&showhidden=true

I tried running duplicati with admin rights as well but it doesn't help.

**Comment by bobambrosius** [comment]
Same here for v2.0.1.18 on WIndows 10 using Edge on laptop (a). On another laptop (b) I have v2.01.1.16 running and there is no problem listing folders in the source data pickers, also WIndows 10 using Edge. However it is strange that, on laptop (a) after removing v2.0.1.18 and installing v2.0.1.16 I still have the folder pickers problem. How can it be that the same version behave different on another computer?

**Comment by kenkendk** [comment]
@stanimirivanovde and @bobambrosius: The problems in 2.0.1.18 are fixed in 2.0.1.20.
