### ISSUE TITLE
[S3 compatible] test connection failed `NameResulationFailure`

### ISSUE THREAD

**Issue by charz** [duplicati/duplicati#2350]
### Version info

**Duplicati Version:** 2.0.1.50
**Operating System:** Windows 7
**Backend:** S3 Compatible 

### Bug description
I have a S3 compatible backed and just try to do a connection test. it shows "NameResulationFailure". And I don't see any request into my backend server.

I can ping my backend service IP and able to use s3cmd to access my s3 backend.

### Steps to reproduce
- Create a new backup
- Setup a backup destination

### Screenshots
![s3_error](https://cloud.githubusercontent.com/assets/620340/23541105/322bb020-0020-11e7-9d3b-4665f08f4077.png)

### debug log
No sure where I can find the client logs.

**Comment by kenkendk** [comment]
You can find the logs via the "Logs" icon to the far left (or the menu top-right on small screens).

It is strange that you get a `NameResolutionFailure` as you have supplied and IP address which should not be looked up. Perhaps you can try using the hostname instead of the IP ?

**Comment by charz** [comment]
@kenkendk thanks for the tip and yes, I see the logs. But it seems like no related log for connection test. 
And I tried another backend storage (OpenStack swift) on same server, it can reach the server without any issue.

**Comment by charz** [comment]
I set a DNS for my local server and it still no lucky.
![s3_fqdn](https://cloud.githubusercontent.com/assets/620340/23545543/c73131fc-0036-11e7-889b-8e36915d94b8.png)

**Comment by Alwaysin** [comment]
Same thing here, but with an IP address, so no name resolution should be involved.

**Comment by cooperaj** [comment]
Seeing this too. 

Connecting using SSL with my host server being "https://storage.example.com". 

A very odd problem.

**Comment by r3dey3** [comment]
I found by adding the advanced option 's3-ext-forcepathstyle' and checking the box fixed my NameResolutionFailure. From: https://groups.google.com/forum/#!topic/duplicati/CcihLY_m5xs

**Comment by kenkendk** [comment]
Not sure why I did not see it before, but yes, if you are using a non Amazon S3 server, you most likely have to disable the DNS lookup (aka `--s3-ext-forcepathstyle`).

I like the idea from @r3dey3, maybe the UI should suggest adding it if the URL is not one of the known S3 endpoints.

**Comment by redge76** [comment]
Yes with with option it works! It should be default for non-S3 endpoints. (or a least we need some warning)

**Comment by kenkendk** [comment]
In the latest canary build I have added a check that sets this option automatically if the server url is not a known Amazon S3 endpoint. The advanced option `--s3-ext-forcepathstyle` can still override this automatic setting, but it should now work without setting it.

This should solve this issue.

**Comment by mentalinc** [comment]
Trying to connect to a Minio server still getting this issue with canary version 2017-09-09

Failed to connect: A WebException with status NameResolutionFailure was thrown.
Minio is setup with ssl using lets encrypt

I can access the webinterface with a browser with no issues.

**Comment by mentalinc** [comment]
Hmm now its working between it now working and working I connected use S3 Browser 6.5.9.
Not sure if that triggered something on the Minio side to enable or set something up. but now working for me.

**Comment by remram44** [comment]
It is still not working for me. Please consider fixing this. Having defaults that don't work with anything should be considered an open issue.

**Comment by zoggdotorg** [comment]
I had the same issue but found that my problem was fixed when I removed the http:// from the endpoint. The server was trying to do a DNS resolution on 'http'. Hope this helps. looks like the endpoint can be a hostname or IP address optionally followed by a colon and port number.

**Comment by kenkendk** [comment]
@mentalinc and  A "name resolution failure" means that the hostname is invalid or does not resolve correctly. Make sure you do not have "http://" in the field with the server name. Only the hostname or IP address should be in that field (port name is also supported). 
An example: `example.com:2345` or `192.168.1.2:6789`.

Also, make sure you use the latest canary or set `--s3-ext-forcepathstyle`.

If you still have problem connecting, please create a new issue or ask for help on https://forum.duplicati.com.

**Comment by bdillahu** [comment]
@kenkendk - "Make sure you do not have "http://" in the field with the server name."

Thanks for this... that wound up being my issue...

**Comment by kirangowda29** [comment]
This issue still coming for me, i am not able to schedule backup to S3.

The error is: 
Amazon.Runtime.AmazonServiceException: A WebException with status NameResolutionFailure was thrown. ---> System.Net.WebException: Error: NameResolutionFailure
