### ISSUE TITLE
Google Drive fails to authorize

### ISSUE THREAD

**Issue by Phantop** [duplicati/duplicati#2379]
Under Duplicati - 2.0.1.53_experimental_2017-03-13 on Linux, using Google Drive as the backup location fails. I get the following error:

> Fatal error
Duplicati.Library.Interface.UserInformationException: Failed to authorize using the OAuth service: Error: TrustFailure (The authentication or decryption has failed.). If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=googledrive ---> System.Net.WebException: Error: TrustFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x00057] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x00011] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x00044] in <bd46d4d4f7964dfa9beea098499ab597>:0 
   --- End of inner exception stack trace ---
  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () [0x00056] in <df389ec2993a4c5d84cc50d023650ee9>:0 
  at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () [0x0004a] in <df389ec2993a4c5d84cc50d023650ee9>:0 
  at Duplicati.Library.JSONWebHelper.GetResponse (Duplicati.Library.Utility.AsyncHttpRequest req, System.Object requestdata) [0x000c7] in <12df122f04f04e1e978b6a375232e42b>:0 
   --- End of inner exception stack trace ---
  at Duplicati.Library.Main.BackendManager.List () [0x00041] in <ab9099cf669b4a44ac3d8ab46230146c>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x0000d] in <ab9099cf669b4a44ac3d8ab46230146c>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x00000] in <ab9099cf669b4a44ac3d8ab46230146c>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x0006c] in <ab9099cf669b4a44ac3d8ab46230146c>:0 

What do I do?

**Comment by Nerdy314159265** [comment]
I'm also having this issue on Duplicati - 2.0.1.47_canary_2017-02-14.

This apparently started on March 1st based on my daily backup that I've been running.

**Comment by kenkendk** [comment]
This is most likely an SSL error.

I have a list of tips for fixing SSL here:
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono

Please let me know if this fixes it.

**Comment by Nerdy314159265** [comment]
This fixed the SSL error for me but I am still unable to connect without accept-any-ssl-certificate enabled.

**Comment by kenkendk** [comment]
@Nerdy314159265 is it the same error trace as posted on top? The error there indicates that the Duplicati OAuth handler's certificate is the problem, but that is the same certificate provider as the update server is using, so I am guessing you are seeing another error?

**Comment by Nerdy314159265** [comment]
@kenkendk I believe that the error at the top was fixed after going through the guide. However, I was having some weird issues with Google certs never verifying in my FreeNAS jail, no matter how many different methods of updating the certs I've tried.

I wish I could provide more information on that issue but I'm unlikely too as I'm moving to FreeNAS Corral and converting over to using Docker instead of jails. Which, by the way, I'd love if you guys made an official Duplicati Docker container for FreeNAS.

**Comment by gmag11** [comment]
This is caused because lack of certificates in Mono. Install `ca-certificates-mono` package. Check https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono and https://www.mono-project.com/download/stable/#download-lin
You do not need to update Mono to latest version, only installing certificates.

**Comment by ts678** [comment]
Not reproducible on recent release. Last report here was from 2017. Is anybody still experiencing this issue on current software?
