### ISSUE TITLE
"Index was outside the bounds of the array" on startup

### ISSUE THREAD

**Issue by racer-coder** [duplicati/duplicati#2870]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows 8.1, 64-bit
- **Browser**: Firefox 56.0.2, 64-bit

## Description

I am unable to configure a new backup on a fresh install of Duplicati.  I get "Index was outside the bounds of the array" on startup, and when trying to figure a new backup, each drop down is empty.  For example, encryption only says "No encryption", and there are no storage types in the drop down.

## Steps to reproduce

1. Download and run 2.0.2.1 beta Aug 1 2017 x64.
2. Deselect "run automatically on startup" (Don't know if this is relevant, I just wanted to try this out before committing to it, and didn't want it always running on my laptop.)
3. Run the Duplicati 2.0 program (found via Windows button, search, type "duplic").  Running this automatically opens a window in my browser, and I have the icon in my system tray.

- **Actual result**:
Error dialog pop up "Index was outside the bounds of the array."  Nothing interesting in the drop downs for creating a new backup.
- **Expected result**:
No errors.  Lots of storage choices.

**Comment by kenkendk** [comment]
I think the problem originates from the "there are no storage types in the drop down" issue.

I have seen this happen when there is an XSRF error (popup dialog with mentioning XSRF). The UI then fails to load the system information and shows empty drop down menus. Usually this can be "fixed" by reloading the page (press F5) and the dialogs work again.

Does reloading the page fix your issue?

**Comment by Pectojin** [comment]
This issue may have been resolved by 80378ae1cc8c5ae8328c49e310954e3c7e85e4df

**Comment by aquatack** [comment]
I get this issue when viewing the Home page of the web UI via my android device (chrome browser), but not from my windows machine (firefox). Refreshing on the chrome browser does not resolve the issue. I'm using version 2.0.2.1_beta_2017-08-01

**Comment by Pectojin** [comment]
@aquatack I don't know for sure that this was resolved, but if it was the change wasn't available before  version 2.0.2.21. 

So it won't be in beta until a newer beta release is out.

**Comment by aquatack** [comment]
Hi @Pectojin, apologies for the newbie question but are you referring to the change in https://github.com/duplicati/duplicati/commit/80378ae1cc8c5ae8328c49e310954e3c7e85e4df? Wasn't this done back in 2015? The use of UtcNow does appear to be in the beta release as far as I can tell (https://github.com/duplicati/duplicati/blob/v2.0.2.1-2.0.2.1_beta_2017-08-01/Duplicati/Server/WebServer/AuthenticationHandler.cs). What am I missing?

**Comment by Pectojin** [comment]
Oh, sorry. I confused two commits related to missing XSRF tokens when i made my original post. 

I was thinking of 9a41cf286712fe025ca07bdc7406eeb672c272d8, which adds additional fixes to the XSRF token issue because the original fix did not help in all cases. This commit disables caching on the index page, which holds the XSRF token.

That commit has been out in canary releases since 2.0.2.18.

**Comment by aquatack** [comment]
@Pectojin, great! that does indeed seem to have fixed the issue (now running 2.0.2.21_canary_2018-03-06). The issue has been a bit intermittent in the past so I'll monitor the situation and update again if it reoccurs. Thanks!

**Comment by Pectojin** [comment]
Great! And thank you for checking in! 

I didn't want to close this issue because I couldn't find anyone to confirm that it worked :)
