### ISSUE TITLE
Advanced options list display issue

### ISSUE THREAD

**Issue by Pectojin** [duplicati/duplicati#2945]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: debug (upstream from github)
- **Operating system**: OSX 10.13.2
- **Backend**: Google Drive and Local storage

## Description

When adding advanced options to a backup I get some pretty weird behavior when I reach 11 options. Until I hit 11 options, they're just listed in the order i add them, but once I add 11 options it'll start acting up. The data will still be in the same order, but the option name and option field type changes.

In my case the retention-policy is suddenly replaced by --send-mail-username (while preserving the retention policy data). Then --retention-policy has replaced --allow-missing-source, still retaining the value "true" but now displaying it as a text field rather than a checkbox.

I've attached two pictures because it's really the easiest way to show it. First picture looks correctly (and has 10 items). Second picture looks all messed up and the only thing I did was add an additional item to the list.

I tried adding various different advanced options and with various data, but it doesn't make any difference. It's just that angular is mishandling the data when it reaches 11+ options.

## Steps to reproduce

1. Edit an existing job or make a new one
2. Add 10 advanced options
3. Take notice of the items in the list and their data
4. Add the 11th option
5. Check for data miss-matching in the list.

In my case the first item was always messed up.

- **Actual result**:
Something happened to the list
- **Expected result**:
Nothing should happen to the list

## Screenshots

<img width="829" alt="screen shot 2017-12-31 at 23 11 25" src="https://user-images.githubusercontent.com/1561484/34464468-b88156a8-ee80-11e7-9633-1325b0e5cadd.png">
<img width="839" alt="screen shot 2017-12-31 at 23 11 10" src="https://user-images.githubusercontent.com/1561484/34464469-b89c0c00-ee80-11e7-8568-d7c9871327ec.png">

**Comment by Pectojin** [comment]
I think I've already found the offending code, but it was a bit difficult for me to explain in a commit message, so created this issue for reference.

I'm just testing my change before making a pull request.

**Comment by kenkendk** [comment]
This was fixed with c05ad79

**Comment by we9v** [comment]
Upgraded from 2.0.2.15_experimental to 2.0.2.17_canary_2018-01-23 today and I'm still having this issue in the Settings>Default Options section. (I haven't checked an individual backup's advanced settings, as I have all of them set globally in Default Options.)

![capture](https://user-images.githubusercontent.com/35498704/35301371-f9fe7804-0050-11e8-8bde-37eb030bf66a.PNG)

![image](https://user-images.githubusercontent.com/35498704/35301383-02bfebee-0051-11e8-8ea9-8413a943b91e.png)

**Comment by Pectojin** [comment]
@we9v that's interesting. I hadn't thought about the advanced options globally. 

It seems like it's using the same template code, so the fix should apply. But I can look into it tomorrow and add some notes on what I find.

**Comment by Pectojin** [comment]
@we9v, It's working well on my machine when looking at `Settings>Default Options` using my new fixes. Next canary release should help you as well.

It should be noted that the javascript may be cached by your browser (I had trouble when I was trying to troubleshoot). So after next upgrade you may need to clear your cache before the fix kicks in.
