### ISSUE TITLE
Monitor file changes to trigger continuous backups [$50]

### ISSUE THREAD

**Issue by captainhook** [duplicati/duplicati#3104]
- [X] I have searched open and closed issues for duplicates.
I am aware #60 was created regarding this for older version of Duplicati. This feature would be exceptionally useful in business environments.

## Description

I used to use Crashplan which would run on a NAS, monitor file changes and then upload any new/changed files. I have managed to setup a DIY version of this using rsync and Inotify on Linux for testing purposes.

In this instance, Duplicati would have to retrieve a list of files changed by a system-level monitoring agent, and then backup those files immediately. This provides a continuous backup environment. In an office, for example, a file accidentally edited 10 minutes ago could be easily restored. Otherwise there would be a dependency on the backup schedule - if this schedule is not regular enough, it can mean data loss. This would work amazingly with the File Versioning currently in Canary builds of Duplicati.

## Potential implement:

1. Run system/kernel level service (inotify on Linux, [FindFirstChangeNotification](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365261(v=vs.85).aspx) or similar Windows, fswatch on MacOS) to monitor file changes
2. Retrieve array of files
3. Run command to trigger backup of those files

**Comment by piegamesde** [comment]
There is another use case: My hard disk is incredibly slow. Just scanning through all the files takes hours, keeping me from doing daily backups. If Duplicati could just run in the background and every time a file changes add it to its "To do list", I could do the backups without having to scan for changes at the beginning.

**Comment by FredericMa** [comment]
+1 for this one!
I was also using Crashplan before.

**Comment by theitsmith** [comment]
I concur. Duplicati is great software, but it takes hours to run backups on my Macs--one has only about 150GB and the other has about 1.5TB, both backups (after the initial run) take around three hours. It's pretty much impossible to run hourly or more frequent backups. Real-time support would be a great addition!

They run much faster on my Windows systems but the datasets are a much smaller and I enabled some Windows-specific features in Duplicati to speed up backup times.

Here's some info for how CrashPlan does near real-time backups in Linux/Mac/Windows (I use CrashPlan Enterprise but am switching from it to Duplicati as they discontinued Windows Server support):

https://support.crashplan.com/Troubleshooting/Real-time_Changes_Not_Detected

If one wanted to help facilitate the development of this ability, how would one go about doing that?

**Comment by Ryonez** [comment]
Just curious if this is being implement?

**Comment by warwickmm** [comment]
The option to use the USN Journal on Windows (NTFS filesystems) was added in version 2.0.3.7 to  improve performance of the file scanning process.

Some related discussion is also occurring [here](https://forum.duplicati.com/t/real-time-backup/263/50).

**Comment by SylwesterZarebski** [comment]
Forum thread [Real-time backup](https://forum.duplicati.com/t/real-time-backup/263/50) mentions that work is done last year by Daniel Gehriger:
> The “real-time” backup feature has been merged into the main branch, and should be part of an upcoming release

I could not find any trace of realtime backup in docs, yet there was a merge from PR: https://github.com/duplicati/duplicati/pull/3184

I think this fact should be advertised in documentation.

**Comment by drwtsn32x** [comment]
@SylwesterZarebski - from what I can see that PR was to enable usage of the USN journal. Enabling the USN option in Duplicati allows it to discover new/changed/deleted files much more quickly than scanning the filesystem.  Certainly a benefit is that it opens the door to more (very) frequent backups.  

Right now the Duplicati UI doesn't let you set a backup schedule where the jobs run more frequently than every 6 minutes.

**Comment by SylwesterZarebski** [comment]
Oh, that's sad. Then this is not real-time at all...

This is a must have functionality for real backup on home computers.

**Comment by warwickmm** [comment]
If I recall correctly, CrashPlan was not actually real-time either.  It would detect changes to the files (instead of performing a full scan), and then back up the changes every 15 minutes.

**Comment by vlsi** [comment]
@warwickmm , CrashPlan was real-time the last time I was using it.

**Comment by drwtsn32x** [comment]
@warwickmm  That is my recollection of CrashPlan Home as well (their older 4.x client) - although I believe you could configure the jobs to run as frequently as once a minute. 

Once a minute with Duplicati would be kind of crazy, you'd end up with up to 1440 versions per day.

If I had a need for realtime backups on a subset of my data I'd probably use something like Dropbox or Onedrive.  I'd still protect the data overall with regular Duplicati backups of course.

**Comment by warwickmm** [comment]
It sounds like CrashPlan watches changes to the file system in real-time, but the backup is still performed at some set frequency:

> The Code42 app backs up new changes to files as often as your backup frequency settings allow. The Code42 app watches the file system in real-time (unless that feature is turned off). When a file changes, the next backup is based on your frequency settings. For example, if the backup frequency is set to 15 minutes, then the changes will back up at the next 15 minute interval.

https://support.code42.com/CrashPlan/6/Configuring/Specify_version_settings#Backup_frequency

**Comment by solf** [comment]
The biggest problem with this issue is that realtime monitoring in duplicati (via USN) doesn't work for long paths (>255 or whatever) as far as I remember.

**Comment by drwtsn32x** [comment]
@solf is that still true?  There's a note on the release of 2.0.3.12 that a long path issue with USN was resolved.

https://github.com/duplicati/duplicati/releases/tag/v2.0.3.12-2.0.3.12_canary_2018-10-23

**Comment by solf** [comment]
@drwtsn32x I'm on 'You are currently running Duplicati - 2.0.4.5_beta_2018-11-28'
As far as I remember, it still doesn't work (my backups with long names do not use USN because I couldn't get it to work, but it's been ages since I've messed with this, I am just waiting for whatever next release will be before I try again).

**Comment by drwtsn32x** [comment]
@solf - Hmm, disappointing!  I can't find an open issue about USN and long paths.  I found this closed one:  https://github.com/duplicati/duplicati/issues/3311

**Comment by ts678** [comment]
#3311 looks like it went into master Nov 8, 2018 and came out here:

[v2.0.4.3-2.0.4.3_canary_2018-11-13](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.3-2.0.4.3_canary_2018-11-13)

> Rewrote path handling across the project to better support long paths, thanks @verhoek

2.0.4.5 beta and 2.0.4.23 beta descended from [v2.0.3.14-2.0.3.14_canary_2018-11-08](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.14-2.0.3.14_canary_2018-11-08) so lack that fix.
I'm not sure about any USN issues, or possible remaining bugs, but I wanted to clarify chronology...

[Understand and troubleshoot frequency and version settings](https://support.code42.com/CrashPlan/4/Troubleshooting/Understand_and_troubleshoot_frequency_and_version_settings) (Version 4 -- the last CrashPlan Home)

> CrashPlan watches the file-system in real-time for new and changed files in your file selection and adds them to a to-do list.

[Continuous backup](https://www.code42.com/features/backup-restore/) (current handling)

> Back up data 96x a day so you’re always ready to recover files when needed. A real-time file watcher looks for new files and file updates, and backs up changes every 15 minutes by default.

So I think their real-time has been watching files for a scheduled backup, and not the backup itself.
The most significant difference I can think of is that Duplicati's monitoring only works on Windows.

**Comment by solf** [comment]
@ts678 thanks for clarifying the timeline.
I'd love to get USN working properly with long paths, but not sure I want to risk using canary build.

**Comment by ts678** [comment]
@solf wrote

> I'd love to get USN working properly with long paths, but not sure I want to risk using canary build.

[v2.0.5.1-2.0.5.1_beta_2020-01-18](https://github.com/duplicati/duplicati/releases/tag/v2.0.5.1-2.0.5.1_beta_2020-01-18) contains previously mentioned Canary fixes and also

> Fix long path issue when path has 259 or 260 characters.

which was not a USN issue specifically, but which you might have seen. Can you see how 2.0.5.1 does?

**Comment by solf** [comment]
@ts678 so far with --usn-policy=On (as per 'command line' option in UI) it's doing this:
2020-02-02 10:21:58 -04 - [Information-Duplicati.Library.Main.Operation.BackupHandler-SkipUsnForVolume]: Performing full scan for volume "F:\"

I haven't had time to try to dig into this yet, but if you have any suggesting why it would be skipping USN, it'd helpful.

**Comment by drwtsn32x** [comment]
@solf - Duplicati is designed to skip USN and require a full scan if it detects any changes in source selection or filtering options.  There may be other situations that trigger a full scan as well.

Run another backup without changing any settings - did you see the "performing full scan" message  again?  If you did, what filesystem is on your F: drive?  Is Duplicati running with elevated rights?

**Comment by solf** [comment]
@drwtsn32x I might have figured out the problem.
It seems like there were no changes on the file system and it was doing full scan every time. After I went and created a couple of new files it seems to have stopped running full scans.

I also tested creating new files in directories with > 250+ path length and it seems to have picked them up for backup (at least according to statistics in backup log).

So USN appears to work properly now with long file names -- which is great! Thanks to everyone involved!

Unfortunately It is still not anywhere fast enough for 'real time' backups (I'll have to keep it at 1-hour intervals):
Time Start 2020-02-02 11:54:28 End 2020-02-02 11:56:39 Duration 00:02:11 
Source Files Examined 88400 (12.73 GB) Opened 0 (0 bytes) Added 0 (0 bytes) Modified 0 (0 bytes) Deleted 0

**Comment by ts678** [comment]
> It seems like there were no changes on the file system and it was doing full scan every time. After I went and created a couple of new files it seems to have stopped running full scans.

That doesn't sound like what it should be doing, however there might also be a timing change at play.

If you were testing and running backups by hand sooner than usual, you might not have had sufficient time for the USN change log (which is a finite size) to overflow. Such an overflow will cause a full scan.

Given your two minute backup, if you use VSS (i.e. --snapshot-policy), that could be a substantial part. Verification download after backup could be another. Unfortunately for speed, both have their value...

**Comment by solf** [comment]
@ts678 I think (and it's a complete speculation on my part) that in order for USN to work it needs to 'record' some initial state; and I'm guessing this doesn't happen properly if there are zero changes in the file set being backed up.

To support this theory I have the following observation -- I have two backup sets which back up the same stuff (to different destinations). I've fixed (USN skipping) one of them via creating a couple of files & running the backup. I've subsequently deleted the files and it kept using USN w/o problems.

However when I started the second backup set -- it had the same USN skipping problem. I had to create a couple of new files and run the second backup set to fix USN problem for the second backup set as well. After the fix I've removed the files -- and it also seems to work fine now.

With regards to the overall speed -- based on my observations (including seeing what is being written to log file and disk activity) -- I think the 'problem' here is just the sheer amount of files being backed up. Whatever Duplicati is doing does appear to depend quite a bit simply on the amount of the files in the backup set. I have other backup sets that are smaller and they perform significantly faster.

I do not use snapshots for the cases being discussed here.

**Comment by ts678** [comment]
Quite possibly there is a transition issue at first use of USN. It does do a full scan the first time, because it doesn't know where it left off last time. If you're super-curious, look at ChangeJournalData table in DB or

https://github.com/duplicati/duplicati/blob/1dbaf360a64ca5cd0790836f4e4c8206f365c106/Duplicati/Library/Main/Operation/BackupHandler.cs#L235-L247

**Comment by d-bykov** [comment]
I would much appreciate this feature too. I'm still looking for a self-hosted solution to replace the CrashPlan, and so far Duplicati seems to be the best option for my requirements, The only thing it lacks is the real-time sync.
It would be nice to see the "Real-time" option in the GUI. Now it's possible to schedule a job to run each 6 minutes, but adding the ability to backup data instantly like some cloud sync and backup tools do would be more preferable.

**Comment by warwickmm** [comment]
It sounds like the remaining `fanotify` features [have been merged](https://github.com/fsnotify/fsnotify/issues/114#issuecomment-732841697) into the 5.9 kernel.  Below are some related issues for other backup solutions that may contain some useful information/discussions:

https://github.com/borgbackup/borg/issues/325
https://github.com/restic/restic/issues/1502

**Comment by Xavron** [comment]
At least for me, post initial backups are running at about 60 seconds. Compared to Deja Dup of 14+ minutes.

In my opinion that is fast enough to allow real-time as even that still has to be able to deal with situations where backups are running and files are changed.

Which is probably what hasn't been done. The real-time mentions were probably just prep work in a little area of the big picture from a bit of forward thinking. Though maybe a bit more is sitting on someone's hard drive.

**Comment by ts678** [comment]
> The real-time mentions were probably just prep work

Which ones does this refer to? All here appear explained.

**Comment by Xavron** [comment]
> > The real-time mentions were probably just prep work
> 
> Which ones does this refer to? All here appear explained.

In reference to some code from some link above posted in this issue.

Its unlikely that they have real-time code in any other way or it would be next to being released and the minimum time would be artificial. So the above stuff appears to have been forward thinking and not actual implementation.

I barely looked at the code so far and they might have not attached realtime or real-time to anything else but based on those two keywords not much shows up. Nothing that shows it being implemented anyway. If you know of something different, I didn't see it here.

**Comment by ts678** [comment]
> Really don't remember what I was looking at when I decided that.

Maybe you followed [this](https://github.com/duplicati/duplicati/issues/3104#issuecomment-554897048) earlier issue comment to [Real-time backup](https://forum.duplicati.com/t/real-time-backup/263/50) in the forum based on a point, but later [point](https://forum.duplicati.com/t/real-time-backup/263/51?u=ts678) there clarified:

> “Real-time” is a bit misleading: this feature does not affect, in any way, the frequency of updates

[Implemented backup based on changes recorded in NTFS USN journal #3184](https://github.com/duplicati/duplicati/pull/3184) was also linked, and that PR did have a TODO with:

> The USN journal records a limited amount of changes, and if backups are spaced too far apart, full scans are required as the data will be incomplete. This has the following implications:

>    Frequent (realtime) backups avoid this problem.

and I don't know if the author was working on it, or saying it would help USN out if it existed. I think it would be a major change moving from a code base which is very version-oriented (and versions have a minimum spacing) to one that is more continuous. Backup versions are a point-in-time view of the files, having a minimum overhead for a version of at least info on all files present.

[How the backup process works](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/)

[2.0.4.5_beta_2018-11-28](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.5-2.0.4.5_beta_2018-11-28) provided

> USN support on Windows

and other OSs don't get it, and on Windows it can go into full scan mode (as mentioned in this post) if backups are too far apart.
Solving that might be possible in the way I'm claiming CrashPlan did it, which is watching and accumulating, but not immediately backing up like a sync program can do. Duplicati seems to somewhat support do-it-yourself filesystem watchers via [changed-files](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#changed-files) however that collects paths and not file data. I think completely scanning a file on any change could be very slow, thus unwanted.
