### ISSUE TITLE
Issues when typing passphrase: backspace and esc

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#976]
_From [Cristian...@gmail.com](https://code.google.com/u/116249282208331315358/) on February 01, 2014 15:55:21_

What steps will reproduce the problem? 1. Run any duplicati command that asks for a passphrase
2. Press backspace
3. Press ESC What is the expected output? What do you see instead? 2. I expect to delete a \* when pressing backspace. However, a new \* is added
3. An exception is thrown and the program exists:
Enter encryption passphrase: An error occured: Duplicati.Library.Interface.Cance
lException
   at Duplicati.Library.Modules.Builtin.ConsolePasswordInput.ReadPassphraseFromC
onsole(Boolean confirm)
   at Duplicati.Library.Modules.Builtin.ConsolePasswordInput.Configure(IDictiona
ry`2 commandlineOptions)
   at Duplicati.Library.Main.Controller.SetupCommonOptions(ISetCommonOptions res
ult, String[]& paths)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths,
Action`1 method)
   at Duplicati.Library.Main.Controller.Restore(String[] paths, IFilter filter)
   at Duplicati.CommandLine.Commands.Restore(List`1 args, Dictionary`2 options,
IFilter filter)
   at Duplicati.CommandLine.Program.Main(String[] args) What version of Duplicati are you using? On what operating system? 2.0, Win7 What backend (destination) are you using? File Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=949_
##

**Comment by kenkendk** [comment]
Assuming this is fixed

**Comment by martinml** [comment]
@kenkendk I think it's not fixed, at least not in v2.0.1.56-2.0.1.56_canary_2017-04-21.

I tried this:
1) start a backup which asks for password twice
2) type "asdf" first time
3) type "asdg", then backspace, then "f"
4) `Duplicati.Library.Interface.UserInformationException: The passphrases do not match`

**Comment by warwickmm** [comment]
This is still an issue in 2.0.5.110.
